apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-service.fullname" . }}-config
  labels:
    {{- include "my-service.labels" . | nindent 4 }}
data:
  APP_ENVIRONMENT: {{ .Values.config.appEnvironment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  CUSTOM_MESSAGE: {{ .Values.config.customMessage | quote }}
