apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "my-service.fullname" . }}

spec:
  maxUnavailable: {{ .Values.global.deployment.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "my-service.selectorLabels" . | nindent 6 }}